### ISSUE TITLE
mypy error when updating aiohttp to 3.7.4

### ISSUE THREAD

**Issue by abhinavk99** [abhinavk99/jikanpy#88]
```bash
(env) PS D:\GithubRepositories\jikanpy> mypy jikanpy
jikanpy\utils.py:23:37: error: Argument 1 to "__get__" of "reify" has incompatible type "Union[Response, ClientResponse]"; expected "_TSelf"
Found 1 error in 1 file (checked 5 source files)
```
This mypy error shows up in `add_jikan_metadata()` for the line `response_dict["headers"] = dict(response.headers)` because it seems like aiohttp.ClientResponse.headers is wrapped in a decorator called `reify` that takes an instance of aiohttp.ClientResponse to get the headers.
